version: '3'
services:
    db:
        container_name: postgres
        image: postgres:15.3-alpine
        restart: always
        shm_size: 128mb
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
        networks:
            - backend-network
    rabbitMQ:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - backend-network
    redis:
        image: redis
        command: redis-server --requirepass Redis2019!
        ports:
            - '6379:6379'
        networks:
            - backend-network
networks:
    backend-network:
        driver: bridge
